apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bff-auth-domivice-dev-cert
  namespace: {{ .Values.global.defaultNamespace }}
spec:
  dnsNames:
    - {{ .Values.global.bffHost }}
  secretName: bff-auth-domivice-dev-tls-secret
  issuerRef:
    name: domivice-cluster-issuer
    kind: ClusterIssuer