apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: domivice-test-db-statefulset
  namespace: domivice-test
spec:
  serviceName: domivice-test-db-service
  replicas: 1
  selector:
    matchLabels:
      app: domivice-test-db
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete # Retain
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: domivice-test-db
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: domivice-test-db-secret
              key: MSSQL_SA_PASSWORD
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - name: data
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
      storageClassName: hostpath # default
---
apiVersion: v1
kind: Service
metadata:
  name: domivice-test-db-service
  namespace: domivice-test
spec:
  selector:
    app: domivice-test-db
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433