apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  namespace: {{ .Values.global.defaultNamespace }}
  labels:
    app: axonserver
spec:
  ports:
  - name: gui
    port: 8024
    targetPort: 8024
  selector:
    app: axonserver
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  namespace: {{ .Values.global.defaultNamespace }}
  labels:
    app: axonserver
spec:
  ports:
  - name: grpc
    port: 8124
    targetPort: 8124
  clusterIP: None
  selector:
    app: axonserver