apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.global.defaultNamespace }}
type: Opaque
data:
  # echo -n "CYVLZRXAPJIAJYZJHYGS" | base64
  MSSQL_SA_PASSWORD: UzNjdXIzUEBzc1cwcmQh