apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-auth-domivice-dev-cert
  namespace: {{ .Values.global.defaultNamespace }}
spec:
  dnsNames:
    - {{ .Values.global.apiHost }}
  secretName: api-auth-domivice-dev-tls-secret
  issuerRef:
    name: domivice-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-server-api-service-dev-cert
  namespace: {{ .Values.global.defaultNamespace }}
spec:
  dnsNames:
    - {{ .Values.serviceName }}
  secretName: identity-server-api-service-dev-tls-secret
  issuerRef:
    name: domivice-cluster-issuer
    kind: ClusterIssuer