apiVersion: v1
kind: Namespace
metadata:
  name: domivice-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-k8s-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-grafana-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: domivice-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-prod
---  
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-staging
