apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # echo -n "CYVLZRXAPJIAJYZJHYGS" | base64
  RABBITMQ_ERLANG_COOKIE: Q1lWTFpSWEFQSklBSllaSkhZR1M=