apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      initContainers:
      - name: users-api-migration
        image: core.harbor.domivice.dev/domivice/users.migration:1.0.0
        command: ['/bin/bash', '-c', '/opt/mssql-tools/bin/sqlcmd -S users-db-service -U sa -P $$MSSQL_SA_PASSWORD -i /sql/InitialMigration.sql; wait;']
        env:
        - name: MSSQL_DATABASE
          value: DomiviceUsers
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-api-secret
              key: MSSQL_SA_PASSWORD
      imagePullSecrets:
      - name: harbor-regcred-secret
      containers:
      - name: users-api
        image: core.harbor.domivice.dev/domivice/users.api:1.0.12
        ports:
        - containerPort: 5004
        - containerPort: 5005
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: users-api-secret
              key: USERS_DB_CS
        - name: RabbitMq__Host 
          value: amqp://guest:guest@rabbitmq:5672
        - name: Loki 
          value: "http://loki-stack.domivice-grafana-dev.svc.cluster.local:3100"  
        - name: IdentityServer__Authority 
          value: https://identity-server-api-service:443  
          
      imagePullSecrets:
      - name: harbor-regcred-secret
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: {{ .Values.namespace }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - protocol: TCP
    name: non-ssl-port
    port: 80
    targetPort: 5004
  - protocol: TCP
    name: ssl-port
    port: 443
    targetPort: 5005
  selector:
    app: users-api