apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-api-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.domivice.dev
    secretName: api-domivice-dev-tls-secret
  rules:
  - host: api.domivice.dev
    http:
      paths:
      - path: /v1/users
        pathType: Prefix
        backend:
          service:
            name: users-api-service
            port:
              number: 443
      - path: /openapi/users
        pathType: Prefix
        backend:
          service:
            name: users-api-service
            port:
              number: 443