apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.erlangSecretName }}
  namespace: {{ .Values.rabbitmq.namespaceOverride }}
type: Opaque
data:
  # echo -n "CYVLZRXAPJIAJYZJHYGS" | base64
  rabbitmq-erlang-cookie: Q1lWTFpSWEFQSklBSllaSkhZR1M=