{{ if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-domivice-dev-cert
spec:
  dnsNames:
    - {{ .Values.sonarqube.ingress.ingressHostName }}
  secretName: {{ .Values.sonarqube.ingress.tlsSecretName }}
  issuerRef:
    name: {{ index .Values "cert-manager" "clusterIssuer" }}
    kind: ClusterIssuer
{{ end -}}    