apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-server-api-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.auth.domivice.dev
    secretName: api-auth-domivice-dev-tls-secret
  rules:
  - host: api.auth.domivice.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: identity-server-api-service
            port:
              number: 443