apiVersion: v1
kind: Pod
metadata:
  name: mongo-init
  namespace: {{ .Values.global.defaultNamespace }}
spec:
  containers:
  - name: init-mongo
    image: mongo:latest
    command: ['bash', '/scripts/mongoInit.sh']
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        valueFrom:
          configMapKeyRef:
            key: root_username
            name: mongodb-conf-configmap
      - name: DOMIVICE_SERVICES_USERNAME
        valueFrom:
          configMapKeyRef:
            key: services_username
            name: mongodb-conf-configmap                  
      - name: MONGO_INITDB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            key: root_password
            name: mongodb-password-secret
      - name: DOMIVICE_SERVICES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: services_password
            name: mongodb-password-secret                  
      - name: MONGO_INITDB_DATABASE
        value: {{ .Values.initDatabase }}            
    volumeMounts:
    - name: mongo-init-volume
      mountPath: /scripts         
  restartPolicy: OnFailure
  volumes:
  - name: mongo-init-volume
    configMap:
      name: mongo-init-configmap    