apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-password-secret
  namespace: {{ .Values.global.defaultNamespace }}
immutable: false
type: Opaque
data:
  root_password: cm9vdHBhc3M=
  services_password: cm9vdHBhc3M=
---
apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-keyfile-secret
  namespace: {{ .Values.global.defaultNamespace }}
immutable: false
type: Opaque
data:
  key: RXNsMDFDZHRuZGlmVXhjK2pJTEpDWGswNVNUOERQOE9DTWIyYVlZcWR1YkdqSU1WN0Rwazd4REVCK3NpeGxhZwo5Q2YyaCtxK3BTOTMwSW1xcmY0Q0xsbDBuNk5BRVR2cDNCa1JVZ2dSRHlnZ3ZEOVMzcm92eDBFeGtLZTFlbXlmCjdoUnpzZHFYZW94QWFKaHpRQ20wTE5PaU9nYkl5YmNXVTJzN1VWNVd6cThiS2JKUHYwbXBHOUtYbTVrcnQ0Z2wKOGJBdHFvZWtpdUlYeFlyWFhnYW9oakNwVWEyMS80TkhpMHpWRXZaNUdxQ3JtcEM4RjZDbzNpK2dZY1NRbHZLOApwTWF2TG1jbmI2MjNjSm95Q3kxWjg2bGJqWW43Zm9SVk9qLzJLVityR1ROcFVVMVRRMWlnblo2M1R4eHlLKys4CmFBUUZJTFJQU25paVVtRXRrcWRMS1ZZTHM2Y1VxZzJZcTd0UUVjbCs4bmZwM2kwYzFweTExUHNJL1VZRzkxZnQKNHEvL0lPY1lkVFJ2Y2ZMQm45T2Vka2VxS1VzZnpXUzEyMU5yYklMODVYc2lsalU2LzU0VjQrdTdxNTBacCszMgpVSXhjM0pJRytMT3VGMkdlblRubUtBSVNqT0ZwUEU1dHE5UDJERGJIeVkvbzZyb1loMkNLdVlibld5bi9ra051CmlNczBUREtyWGhJNmJZR3NkM3pCaGJSYklXRVlUdXhVd0hiNEV1bFpRdVBOLyt2QmVyaEMraGZKVjA2Tmd4TmEKQXhPMks2ZEl3TEZyUTR4QVFaQWZBeVJVS0pUNDkyOVdrTkx2SjJJZldLU1BFWE4yUG04aEc2RWc4Y3RXRGtjMgpGQUhuOUthVGhGdTNuRlVyNzlXc1BiNWpiWG1BbEg2VU1uZVcvYUt6WVlrV3FDSFBnRGxlWUxwK3FTTjVmeXFwCmlVNHBPRDQyM0VySTBGd0xRYWpnS3Y0dzhSODRrbFZ3UnliMjZOYThLaHpEZjVQK2FJdlRTVjhQaUoyOTBCZDgKeHFDeE5GTkxxRUdNNDMxY05uZUJ1dllVd291Z1hjeEdUcnM0bmpMYytOMndlT0RFRGZZWm1tN25qNm56VEd3LwpTbjNZQUJKRmdjT2xNOEJmUXRJQzVTL3hTSE5ncUNwVFo5WlE5RWJ5ZlVtTEdzZlZBL2xFY3lqUmFVYStXcWxSClZYak1za004ZlZmWldKSUdmZDJXRzM4R1hWdi9oMzBoQU5FUGZZdnk0V2h1Q2xndkR3V0szMHN0V0FxZUVwcmYKS1l0a3p1TzhDbGQ5eVN0WXlOSnkvZHZIQTYvK3VtVVRaR2o0dC9ycVBTVHJ1UnNTCg==  