apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-domivice-dev-cert
  namespace: {{ .Values.global.defaultNamespace }}
spec:
  dnsNames:
    - {{ .Values.global.apiHost }}
  secretName: api-domivice-dev-tls-secret
  issuerRef:
    name: domivice-cluster-issuer
    kind: ClusterIssuer