apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-api-ingress
  namespace: {{ .Values.global.defaultNamespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.global.apiHost }}
    secretName: api-domivice-dev-tls-secret
  rules:
  - host: {{ .Values.global.apiHost }}
    http:
      paths:
      - path: /v1/users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: 443
      - path: /openapi/users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: 443