apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # echo -n "CYVLZRXAPJIAJYZJHYGS" | base64
  USERS_DB_CS: U2VydmVyPXVzZXJzLWRiLXNlcnZpY2UsMTQzMztEYXRhYmFzZT1Eb21pdmljZVVzZXJzO1VzZXI9c2E7UGFzc3dvcmQ9UzNjdXIzUEBzc1cwcmQhO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: UzNjdXIzUEBzc1cwcmQh